/-
Copyright (c) 2026 Michael R. Douglas. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Zegarlinski-Specific Concentration Bound

The Borell-Herbst concentration of `Abstract/Concentration.lean`
applied to the global LSI from `global_lsi_of_zegarlinski`.

For a Gibbs measure satisfying Zegarlinski's hypothesis (uniform local
LSI + weak gradient coupling), every Lipschitz observable is sub-
Gaussian with rate `c · (1 − α) / L²`:

  μ({x : F x − E_μ F > t}) ≤ exp(−c·(1−α)·t² / (2 L²)).

This composes the proven `global_lsi_of_zegarlinski` (positivity arm
proved, functional inequality from textbook axiom) with the
right-tail textbook axiom `lipschitz_concentration_of_lsi` (and its
proven left-tail companion) to give a one-sided concentration bound
of the Gibbs measure.
-/

import MarkovSemigroups.Abstract.Concentration
import MarkovSemigroups.DobrushinZegarlinski.GlobalLSI

noncomputable section

namespace MarkovSemigroups.DobrushinZegarlinski

open MeasureTheory MarkovSemigroups.Abstract
open scoped NNReal

variable {Λ : Type*} [Fintype Λ] [DecidableEq Λ]

/-- **Lipschitz concentration from the Zegarlinski hypothesis.**

For a Gibbs measure `μ` consistent with a specification `spec`
generated by `V`, satisfying the uniform local LSI (constant `c > 0`)
and weak coupling (constant `α < 1`), every L-Lipschitz function on
the Euclidean side is sub-Gaussian with rate `c · (1 − α) / L²`:

  μ_eucl({x : F x − E_μ_eucl F > t}) ≤ exp(−c·(1−α)·t² / (2 L²))

where `μ_eucl = spec.toEuclideanMeasure μ` is the L²-transport.

The proof composes:
- `global_lsi_of_zegarlinski` — the global LSI bound with constant `c·(1−α)`.
- `lipschitz_concentration_of_lsi` — the Herbst concentration consequence.

This is the consumption surface for any pphi2N-style application that
needs sub-Gaussian deviations of Lipschitz observables (rather than
the entrywise covariance bound from `EntrywiseCovariance.lean`). -/
theorem lipschitz_concentration_of_zegarlinski
    {spec : GibbsSpec Λ ℝ} {V : EuclideanSpace ℝ Λ → ℝ} {c : ℝ}
    [IsGibbsSpecificationFor spec V]
    (h_local : UniformLocalLSI spec c)
    (h_weak : ZegarlinskiCondition V c)
    (μ : Measure (SpinConfig Λ ℝ)) [IsProbabilityMeasure μ]
    (h_gibbs : IsGibbsMeasure spec μ)
    {F : EuclideanSpace ℝ Λ → ℝ} {L : ℝ≥0}
    (hF_lip : LipschitzWith L F)
    (hF_int : Integrable F (spec.toEuclideanMeasure μ))
    (t : ℝ) (ht : 0 ≤ t) :
    (spec.toEuclideanMeasure μ {x | F x - ∫ y, F y ∂(spec.toEuclideanMeasure μ) > t}).toReal
      ≤ Real.exp (- (c * (1 - h_weak.α)) * t ^ 2 / (2 * (L : ℝ) ^ 2)) :=
  lipschitz_concentration_of_lsi
    (global_lsi_of_zegarlinski h_local h_weak μ h_gibbs)
    hF_lip hF_int t ht

/-- Left-tail companion: `μ({F − E F < −t}) ≤ exp(−c·(1−α)·t²/(2L²))`. -/
theorem lipschitz_concentration_left_of_zegarlinski
    {spec : GibbsSpec Λ ℝ} {V : EuclideanSpace ℝ Λ → ℝ} {c : ℝ}
    [IsGibbsSpecificationFor spec V]
    (h_local : UniformLocalLSI spec c)
    (h_weak : ZegarlinskiCondition V c)
    (μ : Measure (SpinConfig Λ ℝ)) [IsProbabilityMeasure μ]
    (h_gibbs : IsGibbsMeasure spec μ)
    {F : EuclideanSpace ℝ Λ → ℝ} {L : ℝ≥0}
    (hF_lip : LipschitzWith L F)
    (hF_int : Integrable F (spec.toEuclideanMeasure μ))
    (t : ℝ) (ht : 0 ≤ t) :
    (spec.toEuclideanMeasure μ {x | F x - ∫ y, F y ∂(spec.toEuclideanMeasure μ) < -t}).toReal
      ≤ Real.exp (- (c * (1 - h_weak.α)) * t ^ 2 / (2 * (L : ℝ) ^ 2)) :=
  lipschitz_concentration_left_of_lsi
    (global_lsi_of_zegarlinski h_local h_weak μ h_gibbs)
    hF_lip hF_int t ht

/-- **Two-sided Lipschitz concentration on the Gibbs measure.**

  μ_eucl({x : |F x − E F| > t}) ≤ 2 · exp(−c·(1−α)·t² / (2 L²)). -/
theorem lipschitz_concentration_two_sided_of_zegarlinski
    {spec : GibbsSpec Λ ℝ} {V : EuclideanSpace ℝ Λ → ℝ} {c : ℝ}
    [IsGibbsSpecificationFor spec V]
    (h_local : UniformLocalLSI spec c)
    (h_weak : ZegarlinskiCondition V c)
    (μ : Measure (SpinConfig Λ ℝ)) [IsProbabilityMeasure μ]
    (h_gibbs : IsGibbsMeasure spec μ)
    {F : EuclideanSpace ℝ Λ → ℝ} {L : ℝ≥0}
    (hF_lip : LipschitzWith L F)
    (hF_int : Integrable F (spec.toEuclideanMeasure μ))
    (t : ℝ) (ht : 0 ≤ t) :
    (spec.toEuclideanMeasure μ
        {x | t < |F x - ∫ y, F y ∂(spec.toEuclideanMeasure μ)|}).toReal
      ≤ 2 * Real.exp (- (c * (1 - h_weak.α)) * t ^ 2 / (2 * (L : ℝ) ^ 2)) :=
  lipschitz_concentration_two_sided_of_lsi
    (global_lsi_of_zegarlinski h_local h_weak μ h_gibbs)
    hF_lip hF_int t ht

/-- **L^p integrability of Lipschitz F on the Gibbs measure.**

Sub-Gaussian tails ⇒ all moments finite. The centered L-Lipschitz F
is in `L^p(μ_eucl)` for every `p`. -/
theorem memLp_of_zegarlinski
    {spec : GibbsSpec Λ ℝ} {V : EuclideanSpace ℝ Λ → ℝ} {c : ℝ}
    [IsGibbsSpecificationFor spec V]
    (h_local : UniformLocalLSI spec c)
    (h_weak : ZegarlinskiCondition V c)
    (μ : Measure (SpinConfig Λ ℝ)) [IsProbabilityMeasure μ]
    (h_gibbs : IsGibbsMeasure spec μ)
    {F : EuclideanSpace ℝ Λ → ℝ} {L : ℝ≥0}
    (hF_lip : LipschitzWith L F)
    (hF_int : Integrable F (spec.toEuclideanMeasure μ)) (p : ℝ≥0) :
    MeasureTheory.MemLp
      (fun x => F x - ∫ y, F y ∂(spec.toEuclideanMeasure μ)) p
      (spec.toEuclideanMeasure μ) :=
  memLp_of_lsi
    (global_lsi_of_zegarlinski h_local h_weak μ h_gibbs)
    hF_lip hF_int p

/-- **Variance bound for Lipschitz observables on the Gibbs measure.**

  Var_{μ_eucl}(F) ≤ L² / (c · (1 − α)).

This is the spectral-gap-style consequence of LSI, specialized to
Lipschitz observables. -/
theorem variance_lipschitz_le_of_zegarlinski
    {spec : GibbsSpec Λ ℝ} {V : EuclideanSpace ℝ Λ → ℝ} {c : ℝ}
    [IsGibbsSpecificationFor spec V]
    (h_local : UniformLocalLSI spec c)
    (h_weak : ZegarlinskiCondition V c)
    (μ : Measure (SpinConfig Λ ℝ)) [IsProbabilityMeasure μ]
    (h_gibbs : IsGibbsMeasure spec μ)
    {F : EuclideanSpace ℝ Λ → ℝ} {L : ℝ≥0}
    (hF_lip : LipschitzWith L F)
    (hF_diff : Differentiable ℝ F)
    (hF_int : Integrable F (spec.toEuclideanMeasure μ))
    (hF_sq_int :
      Integrable (fun x => (F x) ^ 2) (spec.toEuclideanMeasure μ))
    (hgrad_int :
      Integrable (fun x => ‖fderiv ℝ F x‖ ^ 2)
        (spec.toEuclideanMeasure μ)) :
    ProbabilityTheory.variance F (spec.toEuclideanMeasure μ)
      ≤ ((L : ℝ) ^ 2) / (c * (1 - h_weak.α)) :=
  variance_lipschitz_le_of_lsi
    (global_lsi_of_zegarlinski h_local h_weak μ h_gibbs)
    hF_lip hF_diff hF_int hF_sq_int hgrad_int

/-- **Mathlib `HasSubgaussianMGF` bridge for Zegarlinski.**

The centered Lipschitz observable `F − E F` is sub-Gaussian (in
Mathlib's sense) with variance proxy `L² / (c·(1-α))` against the
Euclidean pushforward of the Gibbs measure. Lets downstream consumers
plug into any Mathlib lemma that expects `HasSubgaussianMGF`. -/
theorem hasSubgaussianMGF_of_zegarlinski
    {spec : GibbsSpec Λ ℝ} {V : EuclideanSpace ℝ Λ → ℝ} {c : ℝ}
    [IsGibbsSpecificationFor spec V]
    (h_local : UniformLocalLSI spec c)
    (h_weak : ZegarlinskiCondition V c)
    (μ : Measure (SpinConfig Λ ℝ)) [IsProbabilityMeasure μ]
    (h_gibbs : IsGibbsMeasure spec μ)
    {F : EuclideanSpace ℝ Λ → ℝ} {L : ℝ≥0}
    (hF_lip : LipschitzWith L F)
    (hF_int : Integrable F (spec.toEuclideanMeasure μ)) :
    ProbabilityTheory.HasSubgaussianMGF
      (fun x => F x - ∫ y, F y ∂(spec.toEuclideanMeasure μ))
      ⟨(L : ℝ) ^ 2 / (c * (1 - h_weak.α)),
        div_nonneg (sq_nonneg _)
          (mul_nonneg h_local.c_pos.le (by linarith [h_weak.α_lt_one]))⟩
      (spec.toEuclideanMeasure μ) :=
  hasSubgaussianMGF_of_lsi
    (global_lsi_of_zegarlinski h_local h_weak μ h_gibbs)
    hF_lip hF_int

end MarkovSemigroups.DobrushinZegarlinski

end
