/-
Copyright (c) 2026 Michael R. Douglas. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Entrywise Covariance Bound from Zegarlinski Hypothesis

This file provides the bridge from the Zegarlinski local-LSI + weak-
coupling hypothesis to entrywise multiplicative bounds on the
covariance `Cov_μ(σ_x, σ_y)` of coordinate functions.

This is the bridge that downstream consumers (e.g., pphi2N's mass-
gap proof via `HSData.AdmitsThimbleLocal`) actually need: not the
global LSI directly, but a *per-(x,y)* bound on the inverse-Hessian
covariance entries. The standard route is the Helffer–Sjöstrand
representation

  Cov_μ(σ_x, σ_y) = ∫ ((Hess V)⁻¹)_{xy} dμ

(valid for log-concave `μ ∝ e^{-V} dx`), combined with the Neumann
expansion `(D + W)⁻¹ = D⁻¹ Σₙ (-D⁻¹ W)ⁿ` where `D` is the diagonal
local-curvature part and `W` the off-diagonal interaction matrix.
Taking absolute values and using `|D⁻¹ W|_{xy} ≤ J_{xy}/c`:

  |((Hess V)⁻¹)_{xy}| ≤ (1/c) · Σₙ ((J/c)ⁿ)_{xy}.

Integrating against `μ`:

  |Cov_μ(σ_x, σ_y)| ≤ (1/c) · Σₙ ((J/c)ⁿ)_{xy}
                     ≤ (1/c) · 1/(1-α)                    (Neumann row bound)

For finite-range interactions, the entrywise iterate vanishes for
`n < d(x, y)/R`, giving exponential decay `α^{d(x,y)/R}/(c · (1-α))`.
That's the form pphi2N consumes for the strict-thermodynamic-limit
mass-gap proof.

## Status

* `neumannEntrywise` — the entrywise Neumann sum, defined and
  bounded by `1/(1-α)` (proven in `AbstractInfluence.lean`).
* `cov_entrywise_bound_of_zegarlinski` — the target theorem, stated
  as a textbook axiom (Helffer–Sjöstrand + log-concavity, NOT VERIFIED).
* For nearest-neighbor finite-range interactions (`d(x,y) > 1 →
  J(x,y) = 0`), the exponential decay form `cov_entrywise_decay_nn`
  is *proved* below from the textbook axiom + the *proved*
  `AbstractInfluenceMatrix.neumann_series_nn_dist_bound`. This is
  the consumption surface for pphi2N's `HSData.AdmitsThimbleLocal`.

## References

* Helffer & Sjöstrand, "On the correlations for Kac-like models in
  the convex case," *J. Stat. Phys.* 74 (1994).
* Naddaf & Spencer, "On homogenization and scaling limit of some
  gradient perturbations of a massless free field," *Comm. Math. Phys.*
  183 (1997).
* Bakry, Gentil, Ledoux, *Analysis and Geometry of Markov Diffusion
  Operators*, Springer, 2014, §4.5 (variance and covariance under
  log-concavity).
-/

import MarkovSemigroups.DobrushinZegarlinski.AbstractInfluence
import MarkovSemigroups.DobrushinZegarlinski.GlobalLSI

noncomputable section

namespace MarkovSemigroups.DobrushinZegarlinski

open MeasureTheory

variable {Λ : Type*} [Fintype Λ] [DecidableEq Λ]

/-- **Entrywise Neumann sum.** For an `AbstractInfluenceMatrix`,
the (x, y) entry of `(I - M)⁻¹` is `Σₙ Mⁿ(x, y)`. This is the
canonical "spatial decay coefficient" between sites x and y. -/
noncomputable def AbstractInfluenceMatrix.neumannEntrywise
    (M : AbstractInfluenceMatrix Λ) (x y : Λ) : ℝ :=
  ∑' n, M.iterate n x y

section
omit [Fintype Λ]

/-- The entrywise Neumann sum is bounded by the resolvent norm
`1/(1-α)`. This is `neumann_series_pointwise_bound` (proved). -/
lemma AbstractInfluenceMatrix.neumannEntrywise_le
    (M : AbstractInfluenceMatrix Λ) (x y : Λ) :
    M.neumannEntrywise x y ≤ (1 - M.α)⁻¹ :=
  M.neumann_series_pointwise_bound x y

/-- The entrywise Neumann sum is nonnegative. -/
lemma AbstractInfluenceMatrix.neumannEntrywise_nonneg
    (M : AbstractInfluenceMatrix Λ) (x y : Λ) :
    0 ≤ M.neumannEntrywise x y :=
  tsum_nonneg fun n => M.iterate_nonneg n x y

end

/-! ## Coordinate functions and covariance -/

/-- The coordinate function at site `x`: maps a configuration to its
value at `x`. Used as the test function for the Helffer-Sjöstrand
covariance representation. -/
def coord (x : Λ) : SpinConfig Λ ℝ → ℝ := fun σ => σ x

/-- Covariance of two coordinate functions under measure `μ`. -/
def covCoord (μ : Measure (SpinConfig Λ ℝ)) (x y : Λ) : ℝ :=
  (∫ σ, σ x * σ y ∂μ) - (∫ σ, σ x ∂μ) * (∫ σ, σ y ∂μ)

/-! ## Main theorem (textbook axiom) -/

/-- **Entrywise covariance bound from Zegarlinski hypothesis.**

Given a Gibbs specification generated by `V`, uniform local LSI with
constant `c > 0`, and Zegarlinski's weak-coupling condition with
constant `α < 1`, the covariance between coordinate spins at sites
`x` and `y` admits the entrywise bound:

  |Cov_μ(σ_x, σ_y)| ≤ (1/c) · `neumannEntrywise (h_weak.toAbstract) x y`
                    ≤ 1/(c · (1 - α))                                (Schur).

For nearest-neighbor finite-range interactions, the entrywise
iterate vanishes below `n = d(x, y)/R` (proved as
`AbstractInfluenceMatrix.iterate_dist_zero` after porting from
`Dobrushin/NeumannSeries.lean`), giving exponential decay
`α^{d(x,y)/R}/(c · (1-α))`.

Reference: Helffer & Sjöstrand, *J. Stat. Phys.* 74 (1994); Naddaf &
Spencer, *Comm. Math. Phys.* 183 (1997); BGL §4.5.

**Hypothesis on h_convex.** The Helffer-Sjöstrand identity strictly
requires `Hess V ≥ c · I` (uniform strict log-concavity). Local LSI
alone is *insufficient*: a double-well potential
`V(x) = x⁴ - 5x² + …` satisfies LSI (by strong-convexity at infinity)
but has negative diagonal Hessian near the origin, breaking the
inverse-Hessian identity. We therefore include `h_convex`
explicitly. By Bakry-Émery, `h_convex` would already imply
`UniformLocalLSI spec c`; we keep both in the signature for
modularity (downstream callers may verify them separately).

Strategy: under log-concavity (encoded by `h_convex` and
`IsGibbsSpecificationFor spec V`), the Helffer–Sjöstrand identity
`Cov_μ(σ_x, σ_y) = ∫ ((Hess V)⁻¹)_{xy} dμ` holds. Decompose
`Hess V = D + W` with `D ≥ c · I` diagonal and `W` off-diagonal
(so `‖D⁻¹ W‖_op ≤ α` by Schur applied to `J/c`). The Neumann
expansion gives the entrywise inverse-Hessian bound
`|((Hess V)⁻¹)_{xy}| ≤ (1/c) · neumannEntrywise(J/c) x y`
pointwise, and integration against `μ` (a probability measure)
completes the proof.

(NOT VERIFIED — axiom stands until peer review.
 GR (Gemini chat, gemini-3-pro-preview): rated `Likely correct`
 after fix for missing `h_convex` hypothesis.) -/
axiom cov_entrywise_bound_of_zegarlinski
    {spec : GibbsSpec Λ ℝ} {V : EuclideanSpace ℝ Λ → ℝ} {c : ℝ}
    [hgen : IsGibbsSpecificationFor spec V]
    (h_local : UniformLocalLSI spec c)
    (h_convex : ∀ (x : Λ) (ψ : EuclideanSpace ℝ Λ),
      c ≤ fderiv ℝ
            (fun ψ' => fderiv ℝ V ψ' (EuclideanSpace.single x 1)) ψ
              (EuclideanSpace.single x 1))
    (h_weak : ZegarlinskiCondition V c)
    (μ : Measure (SpinConfig Λ ℝ)) [IsProbabilityMeasure μ]
    (h_gibbs : IsGibbsMeasure spec μ)
    (x y : Λ)
    (h_x_L2 : Integrable (fun σ : SpinConfig Λ ℝ => (σ x) ^ 2) μ)
    (h_y_L2 : Integrable (fun σ : SpinConfig Λ ℝ => (σ y) ^ 2) μ) :
    |covCoord μ x y| ≤ (1 / c) * (h_weak.toAbstract).neumannEntrywise x y

/-! ## Exponential decay corollary (nearest-neighbor finite-range)

For nearest-neighbor finite-range interactions (J vanishing beyond
distance 1), the entrywise covariance bound has *exponential* decay
in the lattice distance, with rate `α`. -/

/-- **Exponential covariance decay for nearest-neighbor finite-range
interactions.**

Combining the textbook covariance axiom with the proved
`AbstractInfluenceMatrix.neumann_series_nn_dist_bound`: if the
gradient interaction `J_{xy}` vanishes whenever `d(x, y) > 1`, then

  |Cov_μ(σ_x, σ_y)| ≤ α^{d(x,y)} / (c · (1 - α)).

This is the form pphi2N's `HSData.AdmitsThimbleLocal` consumes for
the exponential mass-gap proof in the strict thermodynamic limit.

The hypothesis `h_nn` says `J(x, y) = 0` whenever `d(x, y) > 1`
(nearest-neighbor finite-range). The pseudometric `d` can be the
ℓ¹ lattice distance `latticeDist` (already in the project) or any
other compatible nonneg integer-valued metric. -/
theorem cov_entrywise_decay_nn
    {spec : GibbsSpec Λ ℝ} {V : EuclideanSpace ℝ Λ → ℝ} {c : ℝ}
    [hgen : IsGibbsSpecificationFor spec V]
    (h_local : UniformLocalLSI spec c)
    (h_convex : ∀ (x : Λ) (ψ : EuclideanSpace ℝ Λ),
      c ≤ fderiv ℝ
            (fun ψ' => fderiv ℝ V ψ' (EuclideanSpace.single x 1)) ψ
              (EuclideanSpace.single x 1))
    (h_weak : ZegarlinskiCondition V c)
    (μ : Measure (SpinConfig Λ ℝ)) [IsProbabilityMeasure μ]
    (h_gibbs : IsGibbsMeasure spec μ)
    (d : Λ → Λ → ℕ)
    (h_refl : ∀ x, d x x = 0)
    (h_triangle : ∀ x y z, d x y ≤ d x z + d z y)
    (h_nn : ∀ x y, d x y > 1 → interactionMatrix V x y = 0)
    (x y : Λ)
    (h_x_L2 : Integrable (fun σ : SpinConfig Λ ℝ => (σ x) ^ 2) μ)
    (h_y_L2 : Integrable (fun σ : SpinConfig Λ ℝ => (σ y) ^ 2) μ) :
    |covCoord μ x y| ≤ h_weak.α ^ d x y / (c * (1 - h_weak.α)) := by
  -- Apply the textbook covariance axiom.
  have h_cov := cov_entrywise_bound_of_zegarlinski h_local h_convex h_weak μ
                  h_gibbs x y h_x_L2 h_y_L2
  -- The toAbstract matrix vanishes outside `d ≤ 1` since J does.
  have h_M_support : ∀ a b : Λ,
      d a b > 1 → (h_weak.toAbstract).entry a b = 0 := by
    intro a b hab
    show (if a = b then (0 : ℝ) else interactionMatrix V a b / c) = 0
    have ha_ne_b : a ≠ b := by
      intro heq
      rw [heq, h_refl] at hab
      exact Nat.lt_irrefl 0 (lt_trans Nat.one_pos hab)
    rw [if_neg ha_ne_b, h_nn a b hab, zero_div]
  -- Apply the dist-aware Neumann bound.
  have h_dist :
      (h_weak.toAbstract).neumannEntrywise x y
        ≤ h_weak.α ^ d x y / (1 - h_weak.α) :=
    (h_weak.toAbstract).neumann_series_nn_dist_bound d h_refl h_triangle
      h_M_support x y
  have hc_inv_nn : (0 : ℝ) ≤ 1 / c :=
    div_nonneg zero_le_one h_weak.c_pos.le
  have h_one_sub_pos : 0 < 1 - h_weak.α := by linarith [h_weak.α_lt_one]
  calc |covCoord μ x y|
      ≤ (1 / c) * (h_weak.toAbstract).neumannEntrywise x y := h_cov
    _ ≤ (1 / c) * (h_weak.α ^ d x y / (1 - h_weak.α)) :=
        mul_le_mul_of_nonneg_left h_dist hc_inv_nn
    _ = h_weak.α ^ d x y / (c * (1 - h_weak.α)) := by
        field_simp

/-- **Exponential covariance decay for finite-range R interactions.**

Generalizes `cov_entrywise_decay_nn` to interactions of range `R ≥ 1`.
Combines the textbook covariance axiom with the proved
`AbstractInfluenceMatrix.neumann_series_dist_bound`: if the gradient
interaction `J_{xy}` vanishes whenever `d(x, y) > R`, and `k` satisfies
`n · R < d(x, y)` for all `n < k` (e.g., `k = ⌈d(x, y) / R⌉`), then

  |Cov_μ(σ_x, σ_y)| ≤ α^k / (c · (1 - α)).

The R=1 specialization (`cov_entrywise_decay_nn` above) takes
`k = d(x, y)`. -/
theorem cov_entrywise_decay_finite_range
    {spec : GibbsSpec Λ ℝ} {V : EuclideanSpace ℝ Λ → ℝ} {c : ℝ}
    [hgen : IsGibbsSpecificationFor spec V]
    (h_local : UniformLocalLSI spec c)
    (h_convex : ∀ (x : Λ) (ψ : EuclideanSpace ℝ Λ),
      c ≤ fderiv ℝ
            (fun ψ' => fderiv ℝ V ψ' (EuclideanSpace.single x 1)) ψ
              (EuclideanSpace.single x 1))
    (h_weak : ZegarlinskiCondition V c)
    (μ : Measure (SpinConfig Λ ℝ)) [IsProbabilityMeasure μ]
    (h_gibbs : IsGibbsMeasure spec μ)
    (d : Λ → Λ → ℕ) (R : ℕ) (hR_pos : 0 < R)
    (h_refl : ∀ x, d x x = 0)
    (h_triangle : ∀ x y z, d x y ≤ d x z + d z y)
    (h_range : ∀ x y, d x y > R → interactionMatrix V x y = 0)
    (x y : Λ) (k : ℕ) (hk_strict : ∀ n, n < k → n * R < d x y)
    (h_x_L2 : Integrable (fun σ : SpinConfig Λ ℝ => (σ x) ^ 2) μ)
    (h_y_L2 : Integrable (fun σ : SpinConfig Λ ℝ => (σ y) ^ 2) μ) :
    |covCoord μ x y| ≤ h_weak.α ^ k / (c * (1 - h_weak.α)) := by
  have h_cov := cov_entrywise_bound_of_zegarlinski h_local h_convex h_weak μ
                  h_gibbs x y h_x_L2 h_y_L2
  -- The toAbstract matrix vanishes outside `d ≤ R` since J does.
  have h_M_support : ∀ a b : Λ,
      d a b > R → (h_weak.toAbstract).entry a b = 0 := by
    intro a b hab
    show (if a = b then (0 : ℝ) else interactionMatrix V a b / c) = 0
    have ha_ne_b : a ≠ b := by
      intro heq
      rw [heq, h_refl] at hab
      exact Nat.lt_irrefl 0 (lt_of_lt_of_le hR_pos hab.le)
    rw [if_neg ha_ne_b, h_range a b hab, zero_div]
  have h_dist :
      (h_weak.toAbstract).neumannEntrywise x y
        ≤ h_weak.α ^ k / (1 - h_weak.α) :=
    (h_weak.toAbstract).neumann_series_dist_bound d R hR_pos h_refl h_triangle
      h_M_support x y k hk_strict
  have hc_inv_nn : (0 : ℝ) ≤ 1 / c :=
    div_nonneg zero_le_one h_weak.c_pos.le
  have h_one_sub_pos : 0 < 1 - h_weak.α := by linarith [h_weak.α_lt_one]
  calc |covCoord μ x y|
      ≤ (1 / c) * (h_weak.toAbstract).neumannEntrywise x y := h_cov
    _ ≤ (1 / c) * (h_weak.α ^ k / (1 - h_weak.α)) :=
        mul_le_mul_of_nonneg_left h_dist hc_inv_nn
    _ = h_weak.α ^ k / (c * (1 - h_weak.α)) := by
        field_simp

end MarkovSemigroups.DobrushinZegarlinski

end
